feat(main): add pr command

diff --git a/config/shell/aliases b/config/shell/aliases
--- a/config/shell/aliases
+++ b/config/shell/aliases
@@ -2,5 +2,42 @@
 alias vi="nvim"
 alias vim="nvim"
 
+# Git shortcuts
+alias gs="git status -sb"
+alias gco="git checkout"
+alias gbd="git branch -d"
+alias gp="git pull"
+
+gpp() {
+  local branch
+  branch="$(git branch --show-current)"
+  if [[ -z "$branch" ]]; then
+    echo "gpp: unable to determine current branch" >&2
+    return 1
+  fi
+  if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
+    git push "$@"
+  else
+    git push -u origin "$branch" "$@"
+  fi
+}
+
+gcob() {
+  if [[ -z "$1" ]]; then
+    echo "usage: gcob <branch-name>" >&2
+    return 1
+  fi
+  git checkout -b "$1"
+}
+
 # Conventional commit helper: add all, pick type, enter message
 alias gac="$HOME/.config/git/gac"
+
+# GitHub pull request helpers (requires gh CLI)
+gpr() {
+  "$HOME/.config/git/gpr"
+}
+
+gprm() {
+  "$HOME/.config/git/gpr" --default-base
+}
